const actionTypes = {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS_MENU: 'FETCH_SUCCESS_MENU',
  FETCH_ERROR: 'FETCH_ERROR',
  FILTER_MENU: 'FILTER_MENU',
  FETCH_SUCCESS_CATEGORIES: 'FETCH_SUCCESS_CATEGORIES',
  CATEGORY: 'CATEGORY',
  CLEAR_CATEGORY_SELECTOR: 'CLEAR_CATEGORY_SELECTOR',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  INCREMENT_AMOUNT: 'INCREMENT_AMOUNT',
  DECREMENT_AMOUNT: 'DECREMENT_AMOUNT',
};

export default actionTypes;
